// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRKVqJEkQuUdYNRNfzkN2AB1QGwdhro4',
    appId: '1:24726811242:web:92c331efc19d5ef99ad013',
    messagingSenderId: '24726811242',
    projectId: 'ecom-exam',
    authDomain: 'ecom-exam.firebaseapp.com',
    storageBucket: 'ecom-exam.appspot.com',
    measurementId: 'G-GBWMSGGSCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAFodXpp9hLgE0VsIUZCItknTT_Hdl9GI',
    appId: '1:24726811242:android:036cd9de1bb403499ad013',
    messagingSenderId: '24726811242',
    projectId: 'ecom-exam',
    storageBucket: 'ecom-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfrShKtPO0aYLLDCTgI1uZxY13ksIeIQU',
    appId: '1:24726811242:ios:17ddbe3d82ff26a49ad013',
    messagingSenderId: '24726811242',
    projectId: 'ecom-exam',
    storageBucket: 'ecom-exam.appspot.com',
    iosBundleId: 'com.example.afExam2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfrShKtPO0aYLLDCTgI1uZxY13ksIeIQU',
    appId: '1:24726811242:ios:6cbe41290358965f9ad013',
    messagingSenderId: '24726811242',
    projectId: 'ecom-exam',
    storageBucket: 'ecom-exam.appspot.com',
    iosBundleId: 'com.example.afExam2.RunnerTests',
  );
}
